# Generated by Django 6.0.1 on 2026-02-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='candle',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
        ),
        migrations.AddField(
            model_name='candle',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='В продаже со скидкой'),
        ),
    ]
