# Generated by Django 6.0.1 on 2026-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_candle_discount_percent_candle_is_hit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candle',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AddField(
            model_name='candle',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
