# Generated by Django 6.0.1 on 2026-02-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_remove_candle_aroma_candle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (рус)'),
        ),
        migrations.AddField(
            model_name='candle',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (укр)'),
        ),
        migrations.AddField(
            model_name='candle',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (рус)'),
        ),
        migrations.AddField(
            model_name='candle',
            name='name_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (укр)'),
        ),
    ]
