# Generated by Django 6.0.1 on 2026-02-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_candle_description_ru_candle_description_uk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='name_uk',
        ),
        migrations.AlterField(
            model_name='candle',
            name='description',
            field=models.TextField(verbose_name='Описание (укр)'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название (укр)'),
        ),
    ]
