# Generated by Django 6.0.1 on 2026-02-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_candle_description_uk_remove_candle_name_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (рус)'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='description',
            field=models.TextField(verbose_name='описание RU'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание UA'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название RU'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название UA'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название (укр)'),
        ),
    ]
