# Generated by Django 6.0.1 on 2026-02-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_name_ru_alter_candle_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('city', models.CharField(max_length=100, verbose_name='Населений пункт')),
                ('warehouse', models.CharField(max_length=200, verbose_name='Відділення Нової пошти')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Нотатки')),
                ('agree_to_terms', models.BooleanField(default=False, verbose_name='Згода на обробку персональних даних')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'Новий'), ('processing', 'В обробці'), ('sent', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='candle',
            name='description',
            field=models.TextField(verbose_name='Описание (укр)'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (рус)'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название (укр)'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (рус)'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('candle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.candle')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
            options={
                'verbose_name_plural': 'Товари в замовленні',
            },
        ),
    ]
