# Generated by Django 6.0.1 on 2026-02-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_alter_candle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='warehouse',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Відділення Нової пошти'),
        ),
    ]
