# Generated by Django 6.0.1 on 2026-02-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Оплата карткою'), ('cod', 'Накладений платіж')], default='', max_length=10, verbose_name='Спосіб оплати'),
        ),
    ]
