# Generated by Django 6.0.1 on 2026-02-12 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_test_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Технический код, например relax, gift, home.', unique=True, verbose_name='Код (латиницей)')),
                ('title_uk', models.CharField(max_length=120, verbose_name='Назва (укр)')),
                ('title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название (рус)')),
                ('description', models.TextField(blank=True, verbose_name='Опис / Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Коллекция по настроению',
                'verbose_name_plural': 'Коллекции по настроению',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='candle',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Свеча будет относиться к выбранной коллекции по настроению.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.collection', verbose_name='Коллекция по настроению'),
        ),
    ]
