# Generated by Django 6.0.1 on 2026-02-12 15:18

from django.db import migrations, models


def forwards_copy_description(apps, schema_editor):
    Collection = apps.get_model('shop', 'Collection')
    for c in Collection.objects.all():
        updated = False
        if not getattr(c, 'description_uk', ''):
            c.description_uk = c.description or ''
            updated = True
        if not getattr(c, 'description_ru', ''):
            c.description_ru = c.description or ''
            updated = True
        if updated:
            c.save(update_fields=['description_uk', 'description_ru'])


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_collection_candle_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Опис (укр)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (рус)'),
        ),
        migrations.RunPython(forwards_copy_description, backwards_noop),
    ]
